keywords<-read.table("c:/ibi/apps/R_DATA/RPROGRAM_KEYWORD_COUNTS.csv", header=TRUE, sep=",")
png("C:/ibi/apps/r_data/rprogram_histogram_counts.png", width=520,height=200)
par(mar=c(5,4,4,2)+0.1)
hist(keywords$Count, main="", xlab="Search Counts")
dev.off()
